### ISSUE TITLE
question about building of Qt-VTK-viewer code on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by simonryu** [martijnkoopman/Qt-VTK-viewer#2]
Dear martijnkoopman,

Thank you for your contribution. Finally, I found out the solution for VTK visualization code using Qt.

I successfully installed Qt 5.11.1 (prebuilt version) and VTK 8.1.1 (by building the source code) on Ubuntu 16.04 LTS. Then I cloned Qt-VTK-viewer from this github and opened CMakeLists.txt with QtCreator in order to configure the project. 

However, the "Configure Project" button of my QtCreator is not activated as the following image. Would you help me ASAP ? I tried to change the options for "kits" but that could not solve the problem.

![image](https://user-images.githubusercontent.com/9817432/44103208-90dca078-a026-11e8-8fa2-9940009892df.png)

**Comment by simonryu** [comment]
I failed to configure project using CMakeLists.txt. So, I am trying to make a project using QVTKWidgetPlugin (QVTKWidgetPlugin.dll is copied to qt designer plugins folder.)
When I start qt designer and check out whether QVTKWidgetPlugin is loaded, I ran into the following error from the menu "Tools>From Editor>About Qt Designer Plug-ins...".
Would you help me?

![image](https://user-images.githubusercontent.com/9817432/44185008-cdf87a00-a14c-11e8-8072-dd8bf192580f.png)

**Comment by martijnkoopman** [comment]
Hi Simonryu,

Your Qt Creator Kit is not configured correctly. Therefore it can not configure or build the project.
You need to ensure that Qt, GCC and CMake can be found. You can specify their locations in the Options window (Menu bar > Tools > Options > Kits)

When set-up correctly, you should get something that looks like this:
![kit](https://user-images.githubusercontent.com/15292384/44225747-91e60900-a18e-11e8-899e-3314d30bf920.png)

Regards,
Martijn
