### ISSUE TITLE
duplicate symbol _main

### ISSUE THREAD

**Issue by YuqiChai** [martijnkoopman/Qt-VTK-viewer#5]
Hi!

I tried to compile your code on my Mac, but I get a strange error: (I used cmake GUI for configuration and I'm using Qt 5.11 and VTK 8.1)
`duplicate symbol _main in:
    CMakeFiles/QtVtkViewer.dir/CMakeFiles/3.12.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
    CMakeFiles/QtVtkViewer.dir/main.cpp.o
ld: 1 duplicate symbol for architecture x86_64`

What issue could this be?

Thx!

**Comment by martijnkoopman** [comment]
Hi,

Must say I haven't tried this project on macOS. I mostly develop on Linux and Windows.
What generator do you use in CMake?

Perhaps there should be some additions in CMakeLists.txt to support macOS.

Regards,
Martijn
