### ISSUE TITLE
is this work for QT 5.6, vtk 8.2

### ISSUE THREAD

**Issue by hugcoday** [martijnkoopman/Qt-VTK-viewer#7]
is this work for QT 5.6, vtk 8.2?
I build for error :

[ 10%] Automatic MOC and UIC for target QtVtkViewer
[ 10%] Built target QtVtkViewer_autogen
[ 20%] Building CXX object CMakeFiles/QtVtkViewer.dir/main.cpp.o
/Users/dizhou/workspace/Qt-VTK-viewer/main.cpp:6:10: fatal error: 'QVTKOpenGLWidget.h' file not found
#include <QVTKOpenGLWidget.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/QtVtkViewer.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/QtVtkViewer.dir/all] Error 2
make: *** [all] Error 2

**Comment by martijnkoopman** [comment]
Hi,

I haven't tested this with Qt 5.6. In this repository I'm always assuming the latest version of Qt and VTK.

Did you enable the following CMake options when building VTK?
- VTK_Group_Qt
- Module_vtkGUISupportQtOpenGL

See also [Build-VTK](https://github.com/martijnkoopman/Qt-VTK-viewer/blob/master/doc/Build-VTK.md).

I just commited a smal changel in main.cpp to use [QVTKOpenGLNativeWidget](https://vtk.org/doc/nightly/html/classQVTKOpenGLNativeWidget.html).
