### ISSUE TITLE
Freeze after zoomToExtent

### ISSUE THREAD

**Issue by panda-z** [martijnkoopman/Qt-VTK-viewer#8]
Widget freeze after calling `renderVTK()` in `zoomToExtent()`.

---
Note:
VTK 8.2
QT 5.12.6
MSVC 2019

**Comment by martijnkoopman** [comment]
Code updated to VTK 9.0. Bug fixed.

Tested with:
VTK 9.0
Qt 5.15.1
MSVC 2019 and GCC9
